{% set name = "geoxarray" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geoxarray-{{ version }}.tar.gz
  sha256: 75a7f49b4c81f0c391e752354aec75e41b7e8d322e7b9ae4ae3bd60e3c0cf3bd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=60
    - wheel
    - setuptools-scm
    - pip
  run:
    - python >=3.9
    - xarray
    - pyproj >=2.2

test:
  imports:
    - geoxarray

about:
  home: https://github.com/geoxarray/geoxarray
  summary: Geolocation utilities for xarray objects
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - djhoese
