{% set name = "geoxarray" %}
{% set version = "0.1.0.post0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geoxarray-{{ version }}.tar.gz
  sha256: 16e7d01e9a54b3cfec30d8a0c382db4241c9b6051a09c074b9fceff1b2dcf688

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=42
    - wheel
    - setuptools-scm >=3.4
    - setuptools_scm_git_archive
    - pip
  run:
    - python >=3.9
    - xarray
    - pyproj >=2.2

test:
  imports:
    - geoxarray

about:
  home: https://github.com/geoxarray/geoxarray
  summary: Geolocation utilities for xarray objects
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - djhoese
